openapi: 3.0.0
servers: []
info:
  description: This is a Tennis Booking API for a private Vancouver tennis club that has over 30 tennis courts. Upon completion of this project, it will allow users for immediate requests on court bookings and lesson bookings.
  version: "1.0.0"
  title: Tennis Court Booking API
  contact:
    email: rlee323@my.bcit.ca

tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /health:
    get:
      summary: Gets the health stats 
      operationId: app.get_health_stats
      description: Gets the health stats for all services
      responses: 
        '200':
          description: Successfuly returned a list of tennis booking events
          content: 
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/health'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              

components:
  schemas:
    health:
      required:
      - receiver
      - storage
      - audit
      - processing
      properties:
        receiver:
          type: string
          example: 'running'
        storage:
          type: string
          example: 'running'
        audit:
          type: string
          example: 'running'
        processing:
          type: string
          example: 'running'
      type: object
        
  
